In [2]:
import numpy as np

##  1 ndrarry

####  1.1  ndarray是一个类型  array是创建ndarray函数(构造器)

In [19]:
x1=np.ndarray(shape=(3), dtype=int, buffer=np.array([1,2,3]), offset=0, order="C") 
x2=np.array([4,5,6])

In [20]:
x1

array([1, 2, 3])

In [21]:
x2

array([4, 5, 6])

In [22]:
print(x1)
print(x2)

print(type(x1))
print(type(x2))

[1 2 3]
[4 5 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 1.2 ndarray常用的构造方法

In [24]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
#从0-1  平均出5个数
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.random.random((3,3))

array([[7.26846376e-01, 8.38632428e-01, 7.74885706e-02],
       [7.98396098e-04, 1.87134672e-01, 6.77564542e-01],
       [9.42558691e-01, 6.91892136e-01, 2.67102970e-01]])

In [42]:
#均值0 标准差1的正太分布
np.random.normal(0,1,(3,3))

array([[ 1.25753308, -1.67752299,  2.20887895],
       [ 0.63986419,  1.29493239,  0.30893941],
       [-0.4551489 , -0.79157763, -0.00850627]])

In [44]:
#0-10之间的随机整形数组，（非均匀分布）
np.random.randint(0,10,(3,3))

array([[8, 7, 2],
       [7, 2, 1],
       [9, 7, 3]])

In [45]:
#3*3的单位矩阵
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 1.3 ndarray数组的属性

In [48]:
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[4, 4, 9, 0, 8],
        [1, 1, 9, 6, 4],
        [5, 1, 6, 2, 3],
        [1, 2, 1, 8, 1]],

       [[0, 0, 0, 8, 2],
        [0, 9, 7, 2, 1],
        [8, 2, 2, 4, 3],
        [9, 8, 1, 8, 3]],

       [[3, 5, 3, 5, 4],
        [7, 4, 1, 8, 5],
        [9, 1, 2, 3, 8],
        [5, 1, 8, 7, 1]]])

In [49]:
print('维度',x3.ndim)
print('形状',x3.shape)
print('大小',x3.size)
print('数据类型',x3.dtype)
print('元素大小',x3.itemsize)
print('总大小',x3.nbytes)

维度 3
形状 (3, 4, 5)
大小 60
数据类型 int32
元素大小 4
总大小 240


#### 1.4 ndarray的切片与 Python  list的切片的不同

In [50]:
x1=np.zeros((3,3))
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
x2=x1[:2,:2]
x2

array([[0., 0.],
       [0., 0.]])

In [52]:
x2[0,0]=2
x2

array([[2., 0.],
       [0., 0.]])

In [53]:
x1

array([[2., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ndarray切片返回的是视图 修改视图后源值会变

In [101]:
x1=[0,0,0]

In [102]:
x2=x1[:2]
x2

[0, 0]

In [103]:
x2[0]=2
x2

[2, 0]

In [104]:
x1

[0, 0, 0]

list切片返回的是数值副本 修改副本后源值不变  另外，list没办法按二维切片

#### 1.5 reshape

In [117]:
x1=np.ones(10)
x1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [118]:
x2=x1.reshape(2,5)
x2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [119]:
print(x2)
print(x1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [123]:
x2[0,0]=0
print(x2)
print(x1)
print('-------------------')
x1[9]=6
print(x2)
print(x1)

[[0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 6.]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 6.]
-------------------
[[0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 6.]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 6.]


结论:reshape 返回的也是非副本视图 视图变了 源值跟着变

In [126]:
#另一种写法  newaxis增加一维
x3=x1[:,np.newaxis]
print(x3)
print(x1)

[[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [6.]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 6.]


####  1.6  拼接

In [128]:
x=np.array(range(6)).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
np.concatenate([x,x])  #==np.concatenate([x,x],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [131]:
np.concatenate([x,x],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

垂直栈

In [134]:
np.vstack([x,x])   #==np.concatenate([x,x],axis=0) 

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

水平栈

In [135]:
np.hstack([x,x])   #==np.concatenate([x,x],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

#### 1.7 分裂

In [136]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
x1,x2=np.split(x,[1])
print(x1,x2)

[[0 1 2]] [[3 4 5]]


In [144]:
x3,x4=np.vsplit(x,[1])
x5,x6=np.hsplit(x,[1])
print(x3)
print(x4)
print(x5)
print(x6)

[[0 1 2]]
[[3 4 5]]
[[0]
 [3]]
[[1 2]
 [4 5]]
