https://www.cnblogs.com/mukekeheart/p/9660296.html

In [1]:
import numpy as np
import time

# 找一条从第一行到最后一行最短的通路

In [2]:
D=[[7,0,0,0,0],[3,8,0,0,0],[8,1,0,0,0],[2,7,4,4,0],[4,5,2,6,5]]
# D=[[7,0,0,0,0],[3,8,0,0,0],[8,1,0,0,0]]
D=np.array(D)
# D=np.random.randint(1,10,[10,10])
D

array([[7, 0, 0, 0, 0],
       [3, 8, 0, 0, 0],
       [8, 1, 0, 0, 0],
       [2, 7, 4, 4, 0],
       [4, 5, 2, 6, 5]])

In [3]:
# 递归解法
time_start=time.time()
def MaxSum(r,j,D):
#     print(">",D[r,j])
    if r == len(D)-1:
        return D[r,j]
    else:
        return np.max([MaxSum(r+1,j,D), MaxSum(r+1,j+1,D)]) + D[r,j]
print(MaxSum(0,0,D))
time_end=time.time()
print('totally cost',time_end-time_start)

30
totally cost 0.0


In [13]:
#递推求解
D2=np.zeros(D.shape)
for i in range(0,len(D)):
    i_=len(D)-1-i
    for j in range(0,i_+1):
        if i_==len(D)-1:
            D2[i_,j]=D[i_,j]
        else:
            D2[i_,j]=np.max([D[i_,j]+D2[i_+1,j],D[i_,j]+D2[i_+1,j+1]])
D2
        

array([[30.,  0.,  0.,  0.,  0.],
       [23., 21.,  0.,  0.,  0.],
       [20., 13., 10.,  0.,  0.],
       [ 7., 12., 10., 10.,  0.],
       [ 4.,  5.,  2.,  6.,  5.]])

In [16]:
#递推求解2
D2=np.zeros(len(D))
for i in range(0,len(D)):
    i_=len(D)-1-i
    for j in range(0,i_+1):
        if i_==len(D)-1:
            D2[j]=D[i_,j]
        else:
            D2[j]=np.max([D[i_,j]+D2[j],D[i_,j]+D2[j+1]])
D2

array([30., 21., 10., 10.,  5.])